version: 2

sources:
  - name: bronze
    database: dbt-airflow-project-f1
    schema: bronze
    tables:
      - name: meetings
      - name: sessions
      - name: drivers
      - name: laps
      - name: stints
      - name: pits
      - name: positions
      - name: car_data
      - name: locations
      - name: intervals
      - name: race_control
      - name: team_radio
