f1_warehouse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-airflow-project-f1
      dataset: silver                                          # default; overridden per layer by dbt_project.yml
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      timeout_seconds: 300
      location: europe-west2
