f1_warehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse-dw      # internal Docker hostname
      port: 8123
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      schema: silver
      secure: false
